import type { OllamaEnvConfig } from '../../../shared/backend-contract'

export const EMPTY_OLLAMA_ENV: OllamaEnvConfig = {
  OLLAMA_HOST: '127.0.0.1:11434',
  OLLAMA_CONTEXT_LENGTH: '131072',
  OLLAMA_KEEP_ALIVE: '30m',
  OLLAMA_MAX_LOADED_MODELS: '',
  OLLAMA_NUM_PARALLEL: '1',
  OLLAMA_FLASH_ATTENTION: '1',
  OLLAMA_KV_CACHE_TYPE: 'q8_0',
  OLLAMA_DEBUG: '1',
  OLLAMA_DEBUG_LOG_REQUESTS: '1',
  LLAMA_ARG_CTX_CHECKPOINTS: '0',
  OLLAMA_MODELS: ''
}
